server:
  port: 8765 #服务端口

spring:
  application:
    name: service-feign #服务之间的调用都是根据这个 name

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ #服务注册的url，注册到的eureka服务地址
  instance:
    hostname: localhost #不配置此项，注册的地址会出现非法不是别的字符

feign:
  hystrix:
    enabled: true #打开熔断器