server:
  port: 8764 #服务端口

spring:
  application:
    name: service-ribbon #服务之间的调用都是根据这个 name

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ #服务注册的url，注册到的eureka服务地址
  instance:
    instance-id: ribbon
    hostname: localhost
